[colors]
background = "#282828ee"
text = "#fbf1c7ff"
selection = "#3c3836ff"
selection-text = "#fbf1c7ff"
match = "#d65d0eff"
prompt = "#d65d0eff"
border = "#d65d0eff"

[border]
width = 2
radius = 6

[window]
anchor = "center"
width = 60
height = 12
padding = 18

[font]
name = "FiraCode Nerd Font"
size = 12
