[colors]
background = "#2e3440ee"
text = "#eceff4ff"
selection = "#4c566aff"
selection-text = "#eceff4ff"
match = "#88c0d0ff"
prompt = "#88c0d0ff"
border = "#88c0d0ff"

[border]
width = 2
radius = 6

[window]
anchor = "center"
width = 60
height = 12
padding = 18

[font]
name = "Inter"
size = 12
